export const enum StatusCodes {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  WRONG_PASSWORD = "WRONG_PASSWORD",
  ACCOUNT_ALREADY_EXISTS_UNVERIFIED = "ACCOUNT_ALREADY_EXISTS_UNVERIFIED",
  ACCOUNT_ALREADY_EXISTS_VERIFIED = "ACCOUNT_ALREADY_EXISTS_VERIFIED",
}
